### ISSUE TITLE
EPIC: As an opendatahub developer i want to have pipelines for deployment of odh api core and odh client in jenkins

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-api-core#1]
- [x] Testserver for odhapicore
- [x]  Testserver for odh vuejs
- [x]  Pipeline for odhapicore
- [x]  Pipeline for odh vuejs
- [x]  Pipeline for SuedtirolConsolePG
- [x]  Pipeline for RavenToPostgtres
- [x]  Pipeline for IdentityServerCore
- [x]  Testserver for IdentityServerCore
