### ISSUE TITLE
Epic: Review and complete all Missing Features in ODH Api Core to do the Migration

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-api-core#119]
- [x] Venues Reduced Method
- [x] Venues Filter
- [x] Eventshort POST Methods
- [x] Eventshort Compatibility St.Virtual
- [x] Eventshort Users with Authentication Server
- [x] Keycloak Production Environment Config
- [ ] Redirect old URL to new
- [x] Make sure HGV Alpinebits PUSH Process is working (User etc..)
- [x] STA Recognizing on their calls with a HTTP Interceptor
- [x] STA Sync  Pois / Accommodations with a Route
- [x] EBMS Class Library
- [x] Eventshort Sync
- [x] Add Server and Client side Caching
