### ISSUE TITLE
EPIC: As an opendatahub developer i want to have the raw data from each import stored in a raw data column

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-api-core#178]
- [ ] Add all imports to .net core instance
- [ ] Add rawdata field to Postgres
- [ ] Fill rawdata field on import
