### ISSUE TITLE
EPIC: Transfer all data Collectors to .Net Core

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-api-core#203]
Each data collector should be manageable per Api Call

- [ ] Accommodation LTS
- [ ] Accommodation Room LTS
- [ ] Accommodation Room HGV
- [ ] Activity LTS
- [ ] Poi LTS
- [ ] Venue LTS
- [ ] Gastronomy LTS
- [ ] Measuringpoint LTS
- [ ] Webcams LTS
- [ ] Wine Companies Suedtirol Wein
- [x] Museums SIAG
- [ ] Events LTS
- [x] EventShort Eurac
- [ ] Outdooractive Activities Pois
- [x] Ninja Events
- [x] STA CSV Pois
- [x] MSS Availability
- [x] LCS Availability
