### ISSUE TITLE
EPIC: As a developer i want to have all Open Data Hub importers on the core instance

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-api-core#319]
Deadline: 31 December 2023

- [x] SIAG Museum
- [x] SIAG Weather
- [x] Suedtirol Wein
- [ ] LTS ActivityData
- [ ] LTS PoiData
- [ ] LTS Beacondata
- [ ] LTS Venues
- [ ] LTS Accommodations
- [ ] LTS Accommodation Rooms
- [ ] HGV Accommodation Rooms
- [ ] LTS Measuringpoints
- [ ] LTS Webcams
- [ ] LTS Events
- [x] EBMS Events
- [x] EVENTS CentroTrevi Drin
- [x] DSS Lift
- [x] DSS Slope
- [ ] LTS Snowreport
- [x] STA Vendingpoints
- [x] Accommodation Search Request LTS
- [x] Accommodation Search Request HGV
- [ ] Outdooractive Match ID Sync

**Comment by RudiThoeni** [comment]
this issue will be closed because the importers are being migrated to the new LTS Data api and imported with Infrastructure V2
