### ISSUE TITLE
EPIC: As a tourism developer i want to migrate all Controllers to ODH Api Core

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/odh-api-core#58]
## Next

* [x] GastronomyController.cs
* [x] EventController.cs
* [x] ArticleController.cs
* [x] ODHActivityPoiController.cs
* [ ] AccommodationController.cs
* [x] WebcamController.cs
* [x] CommonController.cs
* [x] WeatherController.cs
* [x] EventShortController.cs

## Postponed/reevaluate
* [x] AlpineBitsController.cs
* [x] LocationController.cs
* [ ] AppSuggestionController.cs --> not relevant at the moment
* [x] GpxController.cs  --> proxy controller because on lts gpx routes cors is not working
* [ ] PackageController.cs  --> not used at the moment
* [ ] SuedtirolTypeController.cs  --> obsolete

## Done

* [x] PoiController.cs
* [x] ActivityController.cs
* [x] OdhTagController.cs

**Comment by RudiThoeni** [comment]
all done
